batch_size: 16
workers: 0
nepoch: 100
model_name: vrcnet_plus
#load_model: log/pretrained/vrcnet_plus_best_dcd_network.pth
#load_model: eval_models/uniform2/network.pth
#load_model: eval_models/dcd_model_for_benchmark.pth
load_model: log/vrcnet_plus_cd_debug_2024-03-11T17:00:03/best_cd_t_network.pth
start_epoch: 0
num_points: 2048
work_dir: log/
flag: eval
loss: cd
loss_opts:
  alpha: 40
  lambda: 0.5
prob_sample: True
prob_ab:
  - 9
  - -1
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 2
epoch_interval_to_val: 2
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

layers: 1, 1, 1, 1
distribution_loss: KLD
knn_list: "16"
pk: 10
local_folding: True
points_label: True
num_coarse_raw: 1024
num_fps: 2048
num_coarse: 2048
over_scale: 2

# test
save_vis: True
eval_emd: True
test_only: True
